name: Run Unittests

on:
  push:
    branches:
      - main
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run unittests
        run: ./run_unittests.sh